spring.application.name=bookstore-api

# Server
server.port=8080

# Azure MySQL DataSource
spring.datasource.url=jdbc:sqlserver://bookstore-mysql-server.database.windows.net:1433;database=bookstore_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30

spring.datasource.username=aronique@bookstore-mysql-server
spring.datasource.password=J.eDwjQ#gX8sUhT
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# JWT
jwt.secret=MySecretKeyForJWTThatIsAtLeast256BitsLongForSecurity1234567890
jwt.expiration=86400000

